SELECT	* FROM sakila.customer;
SELECT first_name, last_name from sakila.customer;
select	last_name, email from sakila.customer;
SELECT	store_id, first_name, last_name, address_id from sakila.customer;
select DISTINCT store_id from sakila.customer;
select	distinct store_id from sakila.customer;
select * from sakila.customer;
SELECT * from	sakila.customer;
select	* from	sakila.customer;
select FIRST_NAME FROM sakila.customer;
select * from sakila.film;
select	* from sakila.language;
select * from sakila.payment;
