insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'caduco');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'caduco');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'caduco');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'caduco');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'caduco');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'ingresado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'enviado');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'en ensayo');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
insert into status_elemento (idStatus_elemento, status_elemento) values (null, 'apto');
